### PR TITLE
Added JSON-RPC 2.0 error data to response

### PR DESCRIPTION
**Pull request by TSchuermans**
As defined in: http://www.jsonrpc.org/specification#error_object

### CODE REVIEW

**Comment by adlawson** [comment]
Hey @TSchuermans, thanks for your changes!

Would you be able to update the tests too? I think it's just a couple of unit tests in [ResponseTest.php](https://github.com/graze/guzzle-jsonrpc/blob/7e0dc22/test/unit/Message/ResponseTest.php) and assertions to the responses in the [functional tests](https://github.com/graze/guzzle-jsonrpc/tree/7e0dc22/test/functional) that's needed.

I'm not sure what's happened to the StyleCI stuff but @sjparkinson might know what's up.

**Comment by TSchuermans** [comment]
Should be updated @adlawson

**Comment by sjparkinson** [comment]
Ah needed to remove the StyleCI required check from the repos settings.

**Comment by adlawson** [comment]
Looks good to me.
Thanks again @TSchuermans (and thanks @sjparkinson for sorting StyleCI) :rocket: :tada:

**Pull request merged**
