### PR TITLE
modernise the development environment a bit

### PR DESCRIPTION
**Pull request by h-bragg**
- Modify the development environment to use docker instead of Vagrant. 
- Update coding standards.

## List of all changes

1. Deleted `Vagrantfile`
1. Updated `.travis.yml` to support more versions
1. moved all commands to `docker`
1. added `docker-compose.yml` file with: `test`/`node`/`composer` services
1. use `graze/composer` to run composer
1. use `graze/php-alpine` to run tests
1. use `node:8` to run the node test server
1. Fixed the markdown in `README.md`
1. Removed the `.lock` files from the `.gitignore` file and committed them
1. Added phpcs linting based on `graze/standards`
1. Added scruitinzer badges to `README`
1. Fixed items flagged by phpcs
1. Updated the `Makefile` with `help`, `lint`, `test-coverage` targets
1. Fixed various scruitinzer issues
1. Fixed some tests that were not being run correctly (namely `BatchFunctionalTest`)

### CODE REVIEW

**Comment by biggianteye** [comment]
A `make help` target would be nice.

**Comment by h-bragg** [comment]
@biggianteye went and did some other bits that spawned from a re-look.

namely committing .lock files because of https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by biggianteye** [comment]
The gitignore file which ignored `composer.lock` is from the skeleton project. Is it worth updating that as well?

**Comment by h-bragg** [comment]
Yeah, we should probably update the skeleton project

**Comment by biggianteye** [comment]
Scrutinizer is failing because of `doctrine/instantiator`. Sigh.

**Comment by h-bragg** [comment]
I am hoping that disabling the tests in scrutiniser will help... lets see...

**Comment by biggianteye** [comment]
I'll review the the guzzle 3/4/5 PRs once this one is merged.

**Pull request merged**
